version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 15432:15432
    environment:
      POSTGRES_PASSWORD: xyz
    networks:
      - postgres-network
    volumes:
      - db-data:/var/lib/postgresql/data/
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # Read-only

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dev.com
      PGADMIN_DEFAULT_PASSWORD: xyz
      PHP_PG_ADMIN_SERVER_HOST: postgres
      PHP_PG_ADMIN_SERVER_PORT: 5432
      PHP_PG_ADMIN_SERVER_DEFAULTDB: postgres
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin/

  fastapi:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 8000:8000
    depends_on:
      - database
      - pgadmin
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge

volumes:
  db-data:
  pgadmin-data: